name: Remote Dispatch Deploy
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: "143.244.133.235"
        username: "root"
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /var/www/fw-core
          git pull origin main
          npm install
          npm run build
          npx kill-port 3000 || true
          pm2 restart all --update-env
          pm2 save
