name: Remote Dispatch Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: "143.244.133.235"
        username: "root"
        password: ${{ secrets.VPS_PASSWORD }} # चाबी की जगह पासवर्ड सेट कर दिया
        script: |
          cd /var/www/fw-core
          git pull origin main
          npm install
          npm run build
          pm2 restart all
          pm2 save
